# Generated by Django 5.2.17 on 2026-08-26 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='apelido')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('purpose', models.CharField(max_length=140, verbose_name='para que serve')),
                ('attributes', models.JSONField(blank=True, default=list, verbose_name='atributos')),
                ('evidence', models.CharField(choices=[('forte', 'Evidência forte'), ('moderada', 'Evidência moderada'), ('limitada', 'Evidência limitada')], default='moderada', max_length=10, verbose_name='evidência')),
                ('dose_per_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='dose por kg')),
                ('dose_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='dose fixa')),
                ('unit', models.CharField(choices=[('g', 'g'), ('mg', 'mg'), ('dose', 'dose')], default='g', max_length=6, verbose_name='unidade')),
                ('dose_note', models.CharField(blank=True, max_length=160, verbose_name='sobre a dose')),
                ('timing', models.CharField(blank=True, max_length=120, verbose_name='quando tomar')),
                ('myth', models.CharField(blank=True, max_length=200, verbose_name='mito')),
                ('fact', models.CharField(blank=True, max_length=240, verbose_name='fato')),
                ('caution', models.CharField(blank=True, max_length=240, verbose_name='cuidado')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'suplemento',
                'verbose_name_plural': 'suplementos',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SupplementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='supplements.supplement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplement_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'suplemento tomado',
                'verbose_name_plural': 'suplementos tomados',
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['user', 'date'], name='supplements_user_id_f629f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'supplement', 'date'), name='um_suplemento_por_dia')],
            },
        ),
    ]
