# Generated by Django 5.2.17 on 2026-08-31 18:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=40, verbose_name='conquista')),
                ('chave', models.CharField(blank=True, default='', max_length=40, verbose_name='ocorrência')),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='desbloqueada em')),
                ('contexto', models.JSONField(blank=True, default=dict, verbose_name='contexto')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='vista em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'conquista',
                'verbose_name_plural': 'conquistas',
                'ordering': ['-unlocked_at', '-id'],
                'indexes': [models.Index(fields=['user', '-unlocked_at'], name='idx_conquista_pessoa')],
                'constraints': [models.UniqueConstraint(fields=('user', 'slug', 'chave'), name='conquista_unica_por_pessoa')],
            },
        ),
    ]
