# Generated by Django 5.2.17 on 2026-09-21 08:17

import avisos.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_inatividade', models.BooleanField(default=True, verbose_name='e-mail quando parar de treinar')),
                ('email_resumo_semanal', models.BooleanField(default=True, verbose_name='resumo semanal por e-mail')),
                ('push_refeicoes', models.BooleanField(default=True, verbose_name='lembrete de refeição no aparelho')),
                ('hora_email', models.TimeField(default=datetime.time(8, 0), verbose_name='hora dos e-mails')),
                ('chave', models.CharField(default=avisos.models._nova_chave, max_length=32, unique=True, verbose_name='chave de descadastro')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_de_aviso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'preferência de aviso',
                'verbose_name_plural': 'preferências de aviso',
            },
        ),
        migrations.CreateModel(
            name='EmailEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('boas_vindas', 'boas-vindas'), ('inatividade', 'sem treinar há 5 dias'), ('resumo_semanal', 'resumo da semana')], max_length=20, verbose_name='tipo')),
                ('referencia', models.CharField(max_length=32, verbose_name='referência')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('erro', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'e-mail enviado',
                'verbose_name_plural': 'e-mails enviados',
                'constraints': [models.UniqueConstraint(fields=('user', 'tipo', 'referencia'), name='um_email_por_pessoa_tipo_e_referencia')],
            },
        ),
    ]
