# Generated by Django 5.2.17 on 2026-09-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAberto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('primeira_abertura', models.DateTimeField(blank=True, null=True, verbose_name='primeira abertura')),
                ('sincronizado_em', models.DateTimeField(auto_now=True, verbose_name='sincronizado em')),
            ],
            options={
                'verbose_name': 'e-mail aberto',
                'verbose_name_plural': 'e-mails abertos',
            },
        ),
        migrations.CreateModel(
            name='EmailBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('motivo', models.CharField(blank=True, max_length=40, verbose_name='motivo (código do Brevo)')),
                ('bloqueado_em', models.DateTimeField(blank=True, null=True, verbose_name='bloqueado em')),
                ('sincronizado_em', models.DateTimeField(auto_now=True, verbose_name='sincronizado em')),
            ],
            options={
                'verbose_name': 'e-mail bloqueado',
                'verbose_name_plural': 'e-mails bloqueados',
            },
        ),
    ]
