# Generated by Django 5.2.17 on 2026-09-21 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='dia')),
                ('name', models.CharField(max_length=64, verbose_name='evento')),
                ('prop_key', models.CharField(blank=True, max_length=64, verbose_name='propriedade')),
                ('prop_value', models.CharField(blank=True, max_length=200, verbose_name='valor')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='contagem')),
                ('users', models.PositiveIntegerField(default=0, verbose_name='pessoas')),
            ],
            options={
                'verbose_name': 'agregado diário',
                'verbose_name_plural': 'agregados diários',
                'indexes': [models.Index(fields=['name', 'day'], name='ag_nome_dia')],
                'constraints': [models.UniqueConstraint(fields=('day', 'name', 'prop_key', 'prop_value'), name='um_agregado_por_dia_evento_propriedade')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='evento')),
                ('props', models.JSONField(blank=True, default=dict, verbose_name='propriedades')),
                ('anon_id', models.CharField(blank=True, max_length=36, verbose_name='id anônimo')),
                ('session_id', models.CharField(blank=True, max_length=36, verbose_name='sessão')),
                ('route', models.CharField(blank=True, max_length=200, verbose_name='rota')),
                ('referrer', models.CharField(blank=True, max_length=300, verbose_name='origem')),
                ('device', models.CharField(blank=True, max_length=12, verbose_name='dispositivo')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='largura')),
                ('theme', models.CharField(blank=True, max_length=8, verbose_name='tema')),
                ('pwa', models.BooleanField(default=False, verbose_name='PWA instalada')),
                ('app_version', models.CharField(blank=True, max_length=20, verbose_name='versão')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now, verbose_name='quando')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'indexes': [models.Index(fields=['name', 'ts'], name='ev_nome_ts'), models.Index(fields=['user', 'ts'], name='ev_user_ts'), models.Index(fields=['anon_id', 'ts'], name='ev_anon_ts')],
            },
        ),
    ]
