# Generated by Django 5.2.17 on 2026-08-23 20:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('category', models.CharField(choices=[('breakfast', 'Café da manhã'), ('main', 'Refeição principal (almoço/jantar)'), ('snack', 'Lanche'), ('supper', 'Ceia')], max_length=12, verbose_name='categoria')),
                ('time', models.TimeField(verbose_name='horário')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordem')),
                ('target_kcal', models.PositiveIntegerField(verbose_name='meta de calorias')),
                ('target_protein_g', models.PositiveSmallIntegerField(verbose_name='meta de proteína (g)')),
                ('target_carb_g', models.PositiveSmallIntegerField(verbose_name='meta de carboidrato (g)')),
                ('target_fat_g', models.PositiveSmallIntegerField(verbose_name='meta de gordura (g)')),
            ],
            options={
                'verbose_name': 'horário de refeição',
                'verbose_name_plural': 'horários de refeição',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'Opção A'), ('B', 'Opção B'), ('C', 'Opção C')], max_length=1)),
                ('scale_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.25'))], verbose_name='fator de escala')),
                ('kcal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('carb_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_options', to='catalog.mealtemplate')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='plans.mealslot')),
            ],
            options={
                'verbose_name': 'opção de refeição',
                'verbose_name_plural': 'opções de refeição',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('done', 'Concluída'), ('skipped', 'Pulada'), ('off_plan', 'Comi outra coisa')], default='pending', max_length=10)),
                ('marked_at', models.DateTimeField(blank=True, null=True, verbose_name='marcada em')),
                ('slot_name', models.CharField(blank=True, max_length=60)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('kcal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('carb_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
                ('chosen_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='plans.mealoption')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='plans.mealslot')),
            ],
            options={
                'verbose_name': 'refeição do dia',
                'verbose_name_plural': 'refeições do dia',
                'ordering': ['-date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='peso na criação (kg)')),
                ('height_cm', models.PositiveSmallIntegerField(verbose_name='altura (cm)')),
                ('age_years', models.PositiveSmallIntegerField(verbose_name='idade')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentário (trabalho sentado, pouco movimento)'), ('light', 'Levemente ativo (caminha um pouco no dia)'), ('moderate', 'Moderadamente ativo (em pé boa parte do dia)'), ('active', 'Muito ativo (trabalho físico)')], max_length=20)),
                ('goal', models.CharField(choices=[('cut', 'Emagrecer'), ('bulk', 'Ganhar massa'), ('maintain', 'Manter o peso')], max_length=10)),
                ('training_days_per_week', models.PositiveSmallIntegerField(default=0)),
                ('formula', models.CharField(default='mifflin_st_jeor', max_length=30)),
                ('bmr_kcal', models.PositiveIntegerField(verbose_name='taxa metabólica basal')),
                ('tdee_kcal', models.PositiveIntegerField(verbose_name='gasto energético total')),
                ('target_kcal', models.PositiveIntegerField(verbose_name='meta calórica')),
                ('protein_g', models.PositiveSmallIntegerField(verbose_name='proteína (g)')),
                ('carb_g', models.PositiveSmallIntegerField(verbose_name='carboidrato (g)')),
                ('fat_g', models.PositiveSmallIntegerField(verbose_name='gordura (g)')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'plano nutricional',
                'verbose_name_plural': 'planos nutricionais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mealslot',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='plans.nutritionplan'),
        ),
        migrations.AddConstraint(
            model_name='mealoption',
            constraint=models.UniqueConstraint(fields=('slot', 'label'), name='unique_label_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='mealoption',
            constraint=models.UniqueConstraint(fields=('slot', 'template'), name='unique_template_per_slot'),
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['user', 'date'], name='plans_meall_user_id_b22088_idx'),
        ),
        migrations.AddConstraint(
            model_name='meallog',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'slot'), name='unique_log_per_slot_per_day'),
        ),
        migrations.AddConstraint(
            model_name='nutritionplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_plan_per_user'),
        ),
        migrations.AddConstraint(
            model_name='mealslot',
            constraint=models.UniqueConstraint(fields=('plan', 'order'), name='unique_slot_order_per_plan'),
        ),
    ]
