# Generated by Django 5.2.17 on 2026-08-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealoption',
            name='label',
            field=models.CharField(choices=[('A', 'Opção A'), ('B', 'Opção B')], max_length=1),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='goal',
            field=models.CharField(choices=[('cut', 'Emagrecer'), ('bulk', 'Ganhar massa'), ('recomp', 'Emagrecer e ganhar massa ao mesmo tempo'), ('maintain', 'Manter o peso')], max_length=10),
        ),
    ]
