# Generated by Django 5.2.17 on 2026-08-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_mealoption_label_alter_nutritionplan_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sentado o dia todo (escritório ou home office) + academia'), ('light', 'Caminha no dia a dia, tarefas domésticas, bicicleta ocasional + academia'), ('active', 'Trabalho em pé ou braçal, ou cardio pesado diário + academia')], max_length=20),
        ),
    ]
