# Generated by Django 5.2.17 on 2026-08-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_nutritionplan_activity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentário / pouco ativo'), ('light', 'Moderadamente ativo'), ('active', 'Altamente ativo')], max_length=20),
        ),
    ]
