# Generated by Django 5.2.17 on 2026-08-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_hydrationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='recipe_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
