# Generated by Django 5.2.17 on 2026-09-05 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_mealoption_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoleDeAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=django.utils.timezone.localdate, verbose_name='dia')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('ml', models.PositiveIntegerField(verbose_name='mililitros')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles_de_agua', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'gole de água',
                'verbose_name_plural': 'goles de água',
                'ordering': ('-registrado_em',),
                'indexes': [models.Index(fields=['user', 'dia', '-registrado_em'], name='plans_goled_user_id_827a81_idx')],
            },
        ),
    ]
