# Generated by Django 5.2.17 on 2026-09-09 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_food_is_premium'),
        ('plans', '0008_goledeagua'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDaListaMarcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(max_length=1, verbose_name='opção')),
                ('semana', models.DateField(verbose_name='início da semana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcacoes', to='catalog.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_marcados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'item marcado na lista',
                'verbose_name_plural': 'itens marcados na lista',
                'constraints': [models.UniqueConstraint(fields=('user', 'food', 'opcao', 'semana'), name='unique_marcacao_por_lista')],
            },
        ),
    ]
