# Generated by Django 5.2.17 on 2026-09-12 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_itemdalistamarcado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAvulsoDaLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='item')),
                ('semana', models.DateField(verbose_name='dia em que entrou')),
                ('marcado', models.BooleanField(default=False, verbose_name='já pegou')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_avulsos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'item avulso da lista',
                'verbose_name_plural': 'itens avulsos da lista',
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'semana', 'nome'), name='unique_item_avulso_por_dia')],
            },
        ),
    ]
