# Generated by Django 5.2.17 on 2026-09-23 13:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_item_avulso_da_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='porcao',
            field=models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=3, verbose_name='porção'),
        ),
    ]
