# Generated by Django 5.2.17 on 2026-09-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_porcao_da_refeicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='meal_style',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='estilo de cardápio na criação'),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='restricoes',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='restrições no dia da criação'),
        ),
    ]
