# Generated by Django 5.2.17 on 2026-09-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_retrato_do_cardapio'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='corrida_dias',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
