# Generated by Django 5.2.17 on 2026-08-26 07:54

import coaching.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80, verbose_name='nome de exibição')),
                ('default_role', models.CharField(choices=[('trainer', 'treinador'), ('nutritionist', 'nutricionista'), ('both', 'treinador e nutricionista')], default='trainer', max_length=12, verbose_name='atuação')),
                ('council_id', models.CharField(blank=True, help_text='CREF para educação física, CRN para nutrição.', max_length=40, verbose_name='registro no conselho')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil profissional',
                'verbose_name_plural': 'perfis profissionais',
            },
        ),
        migrations.CreateModel(
            name='CoachUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('workout', 'treino'), ('nutrition', 'dieta')], max_length=10, verbose_name='assunto')),
                ('message', models.CharField(max_length=160, verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='visto em')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates_sent', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_updates', to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'aviso do profissional',
                'verbose_name_plural': 'avisos do profissional',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['student', 'seen_at'], name='coaching_co_student_f51c79_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('trainer', 'treinador'), ('nutritionist', 'nutricionista'), ('both', 'treinador e nutricionista')], max_length=12, verbose_name='escopo')),
                ('status', models.CharField(choices=[('pending', 'pendente'), ('active', 'ativo'), ('revoked', 'revogado')], default='pending', max_length=10, verbose_name='situação')),
                ('invite_code', models.CharField(default=coaching.models.gerar_codigo, max_length=6, unique=True, verbose_name='código do convite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='aceito em')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_links', to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'vínculo profissional',
                'verbose_name_plural': 'vínculos profissionais',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('professional', 'student'), name='um_vinculo_ativo_por_par')],
            },
        ),
    ]
