# Generated by Django 5.2.17 on 2026-08-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='professionalstudentlink',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='professionalstudentlink',
            name='student',
        ),
        migrations.DeleteModel(
            name='CoachUpdate',
        ),
        migrations.DeleteModel(
            name='ProfessionalProfile',
        ),
        migrations.DeleteModel(
            name='ProfessionalStudentLink',
        ),
    ]
