# Generated by Django 5.2.17 on 2026-08-23 20:55

import accounts.managers
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='sexo')),
                ('birth_date', models.DateField(verbose_name='data de nascimento')),
                ('height_cm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='altura (cm)')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentário (trabalho sentado, pouco movimento)'), ('light', 'Levemente ativo (caminha um pouco no dia)'), ('moderate', 'Moderadamente ativo (em pé boa parte do dia)'), ('active', 'Muito ativo (trabalho físico)')], default='sedentary', max_length=20, verbose_name='nível de atividade')),
                ('goal', models.CharField(choices=[('cut', 'Emagrecer'), ('bulk', 'Ganhar massa'), ('maintain', 'Manter o peso')], default='maintain', max_length=10, verbose_name='objetivo')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('wake_time', models.TimeField(default=datetime.time(7, 0), verbose_name='horário que acorda')),
                ('sleep_time', models.TimeField(default=datetime.time(23, 0), verbose_name='horário que dorme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dietary_tags', models.ManyToManyField(blank=True, help_text='Refeições sugeridas precisam atender a todas as restrições marcadas.', related_name='profiles', to='catalog.dietarytag', verbose_name='restrições e preferências')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('start_time', models.TimeField(verbose_name='horário de início')),
                ('duration_min', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(300)], verbose_name='duração (min)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dia de treino',
                'verbose_name_plural': 'dias de treino',
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('user', 'weekday'), name='unique_training_day_per_weekday')],
            },
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('20')), django.core.validators.MaxValueValidator(Decimal('400'))], verbose_name='peso (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de peso',
                'verbose_name_plural': 'registros de peso',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_weight_per_day')],
            },
        ),
    ]
