# Generated by Django 5.2.17 on 2026-08-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='passo do onboarding'),
        ),
    ]
