# Generated by Django 5.2.17 on 2026-08-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_onboarding_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('cut', 'Emagrecer'), ('bulk', 'Ganhar massa'), ('recomp', 'Emagrecer e ganhar massa ao mesmo tempo'), ('maintain', 'Manter o peso')], default='maintain', max_length=10, verbose_name='objetivo'),
        ),
    ]
