# Generated by Django 5.2.17 on 2026-08-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sentado o dia todo (escritório ou home office) + academia'), ('light', 'Caminha no dia a dia, tarefas domésticas, bicicleta ocasional + academia'), ('active', 'Trabalho em pé ou braçal, ou cardio pesado diário + academia')], default='sedentary', max_length=20, verbose_name='nível de atividade'),
        ),
    ]
