# Generated by Django 5.2.17 on 2026-08-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remap_moderate_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentário / pouco ativo'), ('light', 'Moderadamente ativo'), ('active', 'Altamente ativo')], default='sedentary', max_length=20, verbose_name='nível de atividade'),
        ),
    ]
