# Generated by Django 5.2.17 on 2026-08-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rotulos_de_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kcal_adjustment',
            field=models.SmallIntegerField(default=0, verbose_name='ajuste de calorias'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recalibrated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='recalibrado em'),
        ),
    ]
