# Generated by Django 5.2.17 on 2026-08-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ajuste_de_calorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fat_kcal_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='gordura prescrita (fracao das calorias)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='protein_g_per_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='proteina prescrita (g/kg)'),
        ),
    ]
