# Generated by Django 5.2.17 on 2026-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_fat_kcal_share_profile_protein_g_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='peso-alvo (kg)'),
        ),
    ]
