# Generated by Django 5.2.17 on 2026-08-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_target_weight_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fat_kcal_share',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='protein_g_per_kg',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target_weight_kg',
        ),
    ]
