# Generated by Django 5.2.17 on 2026-08-26 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_fat_kcal_share_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.CharField(max_length=64, verbose_name='identificador da operação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_operations', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'operação sincronizada',
                'verbose_name_plural': 'operações sincronizadas',
                'indexes': [models.Index(fields=['created_at'], name='accounts_sy_created_0be188_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'op_id'), name='uma_operacao_por_pessoa')],
            },
        ),
    ]
