# Generated by Django 5.2.17 on 2026-08-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_syncedoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='meal_style',
            field=models.CharField(choices=[('quick', 'Rápida e econômica'), ('varied', 'Variada e elaborada')], default='varied', max_length=10, verbose_name='estilo de cardápio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='split_preference',
            field=models.CharField(choices=[('focused', 'Poucos grupos por dia'), ('upper_lower', 'Superior e inferior'), ('full_body', 'Corpo todo')], default='focused', max_length=20, verbose_name='divisão de treino'),
        ),
    ]
