# Generated by Django 5.2.17 on 2026-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_onboarding_ganhou_um_passo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='split_preference',
            field=models.CharField(choices=[('one', '1 grupo por dia'), ('two', '2 grupos por dia'), ('three', '3 grupos por dia')], default='three', max_length=20, verbose_name='divisão de treino'),
        ),
    ]
