# Generated by Django 5.2.17 on 2026-08-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_preferencia_antiga_para_grupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDeRecuperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=64, verbose_name='chave')),
                ('tipo', models.CharField(max_length=8, verbose_name='tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'pedido de recuperação de senha',
                'verbose_name_plural': 'pedidos de recuperação de senha',
                'indexes': [models.Index(fields=['tipo', 'chave', 'criado_em'], name='idx_pedido_rec_limite'), models.Index(fields=['criado_em'], name='idx_pedido_rec_retencao')],
            },
        ),
    ]
