# Generated by Django 5.2.17 on 2026-09-01 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_preferencia_de_divisao_confirmada'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('primeiro_admin', 'Primeiro administrador criado'), ('promoveu_staff', 'Deu acesso administrativo'), ('revogou_staff', 'Removeu acesso administrativo')], max_length=32, verbose_name='ação')),
                ('alvo_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail na hora da ação')),
                ('detalhe', models.JSONField(blank=True, default=dict, verbose_name='detalhe')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='quando')),
                ('alvo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acoes_administrativas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='sobre quem')),
                ('ator', models.ForeignKey(blank=True, help_text='Nulo quando a ação veio de um comando de terminal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acoes_administrativas', to=settings.AUTH_USER_MODEL, verbose_name='quem fez')),
            ],
            options={
                'verbose_name': 'registro administrativo',
                'verbose_name_plural': 'registros administrativos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['-criado_em'], name='accounts_re_criado__7eda44_idx'), models.Index(fields=['alvo', '-criado_em'], name='accounts_re_alvo_id_d5d696_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('acao', 'primeiro_admin')), fields=('alvo',), name='um_primeiro_admin_por_pessoa')],
            },
        ),
    ]
