# Generated by Django 5.2.17 on 2026-09-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_registro_administrativo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registroadministrativo',
            constraint=models.UniqueConstraint(condition=models.Q(('acao', 'primeiro_admin')), fields=('alvo',), name='um_primeiro_admin_por_pessoa'),
        ),
    ]
