# Generated by Django 5.2.17 on 2026-09-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_registro_administrativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('pedir_nova_escolha_de_divisao', 'Pode pedir que a pessoa escolha a divisão de treino de novo')], 'verbose_name': 'perfil', 'verbose_name_plural': 'perfis'},
        ),
    ]
