# Generated by Django 5.2.17 on 2026-09-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_permissao_nova_escolha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroadministrativo',
            name='acao',
            field=models.CharField(choices=[('primeiro_admin', 'Primeiro administrador criado'), ('promoveu_staff', 'Deu acesso administrativo'), ('revogou_staff', 'Removeu acesso administrativo'), ('pediu_nova_divisao', 'Pediu nova escolha de divisão de treino')], max_length=32, verbose_name='ação'),
        ),
    ]
