# Generated by Django 5.2.17 on 2026-09-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_acao_nova_divisao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('ver_painel_de_gestao', 'Pode ver o painel de gestão')], 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.AddField(
            model_name='user',
            name='classificacao',
            field=models.CharField(choices=[('nao_classificada', 'Não classificada'), ('pessoa', 'Pessoa usando o app'), ('demo', 'Demonstração'), ('qa_interno', 'Teste interno')], default='nao_classificada', max_length=20, verbose_name='classificação'),
        ),
    ]
