# Generated by Django 5.2.17 on 2026-09-04 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_painel_de_gestao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenDeApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True, verbose_name='digest')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('expira_em', models.DateTimeField(verbose_name='expira em')),
                ('revogado_em', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
                ('ultimo_uso_em', models.DateTimeField(blank=True, null=True, verbose_name='último uso em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_de_app', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'token de app',
                'verbose_name_plural': 'tokens de app',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['user', '-criado_em'], name='accounts_to_user_id_694234_idx')],
            },
        ),
    ]
