# Generated by Django 5.2.17 on 2026-09-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_token_de_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaDeEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=64, verbose_name='chave')),
                ('tipo', models.CharField(max_length=16, verbose_name='tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'tentativa de entrada',
                'verbose_name_plural': 'tentativas de entrada',
                'indexes': [models.Index(fields=['tipo', 'chave', 'criado_em'], name='accounts_te_tipo_df0e89_idx')],
            },
        ),
    ]
