# Generated by Django 5.2.17 on 2026-09-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    """Só o RÓTULO dos pilares. Nenhum dado se move, nenhum valor muda.

    Os cinco `value` — `dieta`, `treino`, `corrida`, `hidratacao`,
    `progresso` — continuam idênticos: eles são identificador, e estão em
    banco, no `CheckConstraint`, em `CAMPO_DO_PILAR` e no formulário. O que
    mudou é o texto que a pessoa lê: "Musculação" virou "Treino" e "Evolução"
    virou "Progresso", porque o produto passou a ter um nome só por área.

    `choices` não existe no PostgreSQL — é validação do Django. Esta migration
    é, no banco, um no-op; ela existe porque o `makemigrations --check` do
    hook compara o estado declarado, e um estado divergente quebraria o build
    do deploy sem ter nada a ver com o que quebrou.

    `dieta` continuar valendo "Alimentação" é a prova de que os dois planos são
    separáveis: a tela foi renomeada e nenhuma linha foi reescrita.
    """

    dependencies = [
        ('accounts', '0024_pilares_e_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('dieta', 'Alimentação'), ('treino', 'Treino'), ('corrida', 'Corrida'), ('hidratacao', 'Hidratação'), ('progresso', 'Progresso')], default='', max_length=20, verbose_name='prioridade principal'),
        ),
    ]
