"""Perfil novo nasce em "Padrão — 45 a 60", e não em "sem limite rígido".

ISTO É O CONSERTO DE VERDADE, e a `0029` sozinha não era ele. Eu escrevi lá que
`duracao_treino == ""` tinha deixado de ser "ainda não respondeu" — e `""` nunca
acontece pelo ORM: o campo sempre teve `default`, e a `0026` converteu todo
mundo que já existia a partir do `duration_min`. Medido no banco de
desenvolvimento: 165 em `padrao`, 48 em `rapido`, 42 em `completo`, ZERO em
branco. A `0029` fica como rede para linha escrita fora do ORM, e não faz mal
nenhum; o buraco real era o `default` do campo.

O default era `LIVRE`, e estava certo enquanto a pergunta existia na
configuração: presumir um teto que ninguém pediu é pior que não ter teto. A
pergunta saiu da tela em 10/09/2026 — ela pedia uma calibração que ninguém
consegue fazer antes de ver uma ficha —, e com isso o argumento se inverteu:
quem entra hoje NÃO PODE responder, então `LIVRE` deixaria todo perfil novo
montando ficha sem limite. Medido: `abc2 C` sem teto tem doze exercícios e 88
minutos.

O QUE ESTA MIGRATION NÃO FAZ: ela não toca em UMA linha sequer. `AlterField` de
`default` muda só o que o Python escreve dali para frente — o PostgreSQL nem
recebe DDL de valor, porque o Django resolve `default` na aplicação. Quem
escolheu "sem limite rígido" continua sem limite, e é essa a razão de não haver
`RunPython` aqui: não existe jeito de distinguir quem escolheu `livre` de quem
o recebeu por omissão, e reescrever os dois apagaria uma resposta real.

Reversível de graça: a volta devolve o default antigo e continua sem tocar em
dado.
"""
# Generated by Django 5.2.17 on 2026-09-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_duracao_padrao_para_quem_nao_respondeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='duracao_treino',
            field=models.CharField(choices=[('rapido', 'Rápido — até 30 minutos'), ('padrao', 'Padrão — 45 a 60 minutos'), ('completo', 'Completo — 60 a 90 minutos'), ('livre', 'Sem limite rígido — priorizar a ficha completa')], default='padrao', max_length=10, verbose_name='duração do treino'),
        ),
    ]
