"""`Profile.plano`: Grátis ou Pro, e todo mundo nasce (e fica) Grátis.

A coluna entra com default constante `"gratis"`. No PostgreSQL 11+ isso é
mudança de CATÁLOGO — o valor é anotado na definição da coluna e as linhas
existentes não são reescritas (§66: dados existentes são sagrados). O Django
emite `ADD COLUMN ... DEFAULT 'gratis' NOT NULL` e em seguida `DROP DEFAULT`,
porque o default passa a ser resolvido em Python; nenhuma linha muda de
valor, e ninguém vira Pro por migration.

Quem decide o que cada plano alcança é `accounts/gates.py`, e só ele. Este
campo é dado, não regra. Não existe cobrança neste repositório: até existir,
é o admin quem escreve `"pro"` aqui, à mão.
"""
# Generated by Django 5.2.17 on 2026-09-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_duracao_padrao_para_perfil_novo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plano',
            field=models.CharField(choices=[('gratis', 'Grátis'), ('pro', 'Pro')], default='gratis', max_length=10, verbose_name='plano'),
        ),
    ]
