# Generated by Django 5.2.17 on 2026-09-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_onboarding_em_tres_etapas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='duracao_treino',
            field=models.CharField(choices=[('rapido', 'Rápido — até 30 minutos'), ('padrao', 'Padrão — até 60 minutos'), ('completo', 'Completo — a sessão inteira, até 65 minutos'), ('livre', 'Sem limite rígido — o mesmo que Completo, até 65 minutos')], default='padrao', max_length=10, verbose_name='duração do treino'),
        ),
    ]
