# Generated by Django 5.2.17 on 2026-09-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_apaga_token_de_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rastrear_uso',
            field=models.BooleanField(default=True, verbose_name='permitir análise de uso'),
        ),
    ]
