# Generated by Django 5.2.17 on 2026-09-22 01:34
"""Os legais publicados com consentimento (decisão do dono, 21/09/2026).

Duas colunas no perfil e a tabela de prova. E UMA decisão de dado, escrita
aqui para não ser inferida: TODA conta que existia no deploy é marcada com
`precisa_consentir=True` — ela nunca viu as caixas, e a LGPD não tem base
para dado de saúde sem consentimento (art. 11, I). Essas pessoas passam uma
vez por `/conta/consentimento/` antes de qualquer tela; "Excluir minha
conta" continua aberta. Só perfis com o cadastro TERMINADO: quem estava no
meio ainda vai passar pela etapa 1, que pede as caixas. As contas do demo
(`*.demo@nutriplan.invalid`, semeadas — ver `demo/middleware.py`) e as de QA
(`*@nutriplan.invalid`) ficam de fora: não são gente, e a capa pública abre
o demo sem login.
"""

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

ONBOARDING_DONE = 7


def marcar_quem_ja_existia(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    Profile.objects.filter(onboarding_step__gte=ONBOARDING_DONE).exclude(
        user__email__iendswith="@nutriplan.invalid"
    ).update(precisa_consentir=True)


def desmarcar(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    Profile.objects.update(precisa_consentir=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_profile_rastrear_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consentimento_versao',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='versão dos legais consentida'),
        ),
        migrations.AddField(
            model_name='profile',
            name='precisa_consentir',
            field=models.BooleanField(default=False, verbose_name='precisa consentir'),
        ),
        migrations.CreateModel(
            name='Consentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('termos', 'Termos de Uso e Política de Privacidade'), ('saude', 'Dados de saúde'), ('transferencia', 'Transferência internacional')], max_length=16, verbose_name='tipo')),
                ('versao', models.CharField(max_length=10, verbose_name='versão dos legais')),
                ('dado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consentimento',
                'verbose_name_plural': 'consentimentos',
                'constraints': [models.UniqueConstraint(fields=('user', 'tipo', 'versao'), name='um_consentimento_por_versao')],
            },
        ),
        migrations.RunPython(marcar_quem_ja_existia, desmarcar),
    ]
