# Generated by Django 5.2.17 on 2026-09-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_consentimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='musculacao',
            field=models.CharField(blank=True, choices=[('sim', 'Sim, faço musculação'), ('nao', 'Não faço — só corrida, natação ou outro esporte')], default='', max_length=3, verbose_name='faz musculação'),
        ),
    ]
