# Generated by Django 5.2.17 on 2026-08-24 07:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('muscle_group', models.CharField(choices=[('chest', 'Peito'), ('back', 'Costas'), ('quads', 'Quadríceps'), ('hamstrings', 'Posterior de coxa e glúteo'), ('calves', 'Panturrilha'), ('shoulders', 'Ombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('core', 'Abdômen e core')], max_length=12, verbose_name='grupo muscular')),
                ('is_compound', models.BooleanField(default=False, verbose_name='multiarticular')),
                ('cue', models.CharField(blank=True, help_text='Uma frase com o erro mais comum ou o ponto que garante a técnica.', max_length=200, verbose_name='dica de execução')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'exercício',
                'verbose_name_plural': 'exercícios',
                'ordering': ['muscle_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('split', models.CharField(choices=[('full', 'Corpo inteiro'), ('ab', 'AB — superior e inferior'), ('abc', 'ABC — empurrar, puxar e pernas'), ('abcd', 'ABCD — peito, costas, pernas e ombros')], max_length=6, verbose_name='divisão')),
                ('days_per_week', models.PositiveSmallIntegerField(verbose_name='dias por semana')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rotina de treino',
                'verbose_name_plural': 'rotinas de treino',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(verbose_name='dia da semana')),
                ('label', models.CharField(max_length=1, verbose_name='letra')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('focus', models.CharField(blank=True, max_length=120, verbose_name='foco')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='horário')),
                ('duration_min', models.PositiveSmallIntegerField(default=60, verbose_name='duração (min)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.trainingplan')),
            ],
            options={
                'verbose_name': 'treino da semana',
                'verbose_name_plural': 'treinos da semana',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='séries')),
                ('rep_min', models.PositiveSmallIntegerField(default=8, verbose_name='repetições (mín)')),
                ('rep_max', models.PositiveSmallIntegerField(default=12, verbose_name='repetições (máx)')),
                ('measure', models.CharField(choices=[('reps', 'Repetições'), ('seconds', 'Segundos')], default='reps', max_length=8)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(300)], verbose_name='descanso (s)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='workouts.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.trainingsession')),
            ],
            options={
                'verbose_name': 'exercício da ficha',
                'verbose_name_plural': 'exercícios da ficha',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split', models.CharField(choices=[('full', 'Corpo inteiro'), ('ab', 'AB — superior e inferior'), ('abc', 'ABC — empurrar, puxar e pernas'), ('abcd', 'ABCD — peito, costas, pernas e ombros')], max_length=6, verbose_name='divisão')),
                ('label', models.CharField(max_length=1, verbose_name='letra')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('focus', models.CharField(blank=True, max_length=120, verbose_name='foco')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'treino (modelo)',
                'verbose_name_plural': 'treinos (modelos)',
                'ordering': ['split', 'order'],
                'constraints': [models.UniqueConstraint(fields=('split', 'label'), name='unique_label_per_split')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='séries')),
                ('rep_min', models.PositiveSmallIntegerField(default=8, verbose_name='repetições (mín)')),
                ('rep_max', models.PositiveSmallIntegerField(default=12, verbose_name='repetições (máx)')),
                ('measure', models.CharField(choices=[('reps', 'Repetições'), ('seconds', 'Segundos')], default='reps', max_length=8)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(300)], verbose_name='descanso (s)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_items', to='workouts.exercise')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workouts.workouttemplate')),
            ],
            options={
                'verbose_name': 'exercício do treino',
                'verbose_name_plural': 'exercícios do treino',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='trainingplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_routine_per_user'),
        ),
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.UniqueConstraint(fields=('plan', 'weekday'), name='unique_session_per_weekday'),
        ),
        migrations.AddConstraint(
            model_name='workouttemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'exercise'), name='unique_exercise_per_template'),
        ),
    ]
