# Generated by Django 5.2.17 on 2026-08-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link de um vídeo demonstrando o movimento. Guardamos o endereço normal (o que se copia da barra do navegador); a tela converte para embed na hora.', verbose_name='vídeo de execução'),
        ),
    ]
