# Generated by Django 5.2.17 on 2026-08-24 23:08

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_exerciselog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciselog',
            options={'ordering': ['-date', 'set_number'], 'verbose_name': 'carga registrada', 'verbose_name_plural': 'cargas registradas'},
        ),
        migrations.RemoveConstraint(
            model_name='exerciselog',
            name='unique_load_per_exercise_per_day',
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='set_number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='série'),
        ),
        migrations.AddConstraint(
            model_name='exerciselog',
            constraint=models.UniqueConstraint(fields=('user', 'exercise', 'date', 'set_number'), name='unique_load_per_set_per_day'),
        ),
    ]
