# Generated by Django 5.2.17 on 2026-08-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_load_per_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('chest', 'Peito'), ('back', 'Costas'), ('quads', 'Quadríceps'), ('hamstrings', 'Posterior de coxa e glúteo'), ('calves', 'Panturrilha'), ('shoulders', 'Ombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('core', 'Abdômen e core'), ('traps', 'Trapézio'), ('forearms', 'Antebraço')], max_length=12, verbose_name='grupo muscular'),
        ),
    ]
