# Generated by Django 5.2.17 on 2026-08-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_grupos_trapezio_e_antebraco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='split',
            field=models.CharField(choices=[('full', 'Corpo inteiro'), ('ab', 'AB — superior e inferior'), ('abc', 'ABC — empurrar, puxar e pernas'), ('abcd', 'ABCD — peito/tríceps, costas/bíceps, ombro/perna e complementares')], max_length=6, verbose_name='divisão'),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='split',
            field=models.CharField(choices=[('full', 'Corpo inteiro'), ('ab', 'AB — superior e inferior'), ('abc', 'ABC — empurrar, puxar e pernas'), ('abcd', 'ABCD — peito/tríceps, costas/bíceps, ombro/perna e complementares')], max_length=6, verbose_name='divisão'),
        ),
    ]
