# Generated by Django 5.2.17 on 2026-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_divisao_abcde'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='frames',
            field=models.JSONField(blank=True, default=list, verbose_name='quadros da demonstração'),
        ),
    ]
