# Generated by Django 5.2.17 on 2026-08-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_demonstracao_em_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='animation_url',
            field=models.URLField(blank=True, verbose_name='animação de execução'),
        ),
    ]
