# Generated by Django 5.2.17 on 2026-08-26 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_animacao_de_execucao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='prescribed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='prescrita em'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_plans', to=settings.AUTH_USER_MODEL, verbose_name='prescrita por'),
        ),
    ]
