# Generated by Django 5.2.17 on 2026-08-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_trainingplan_prescribed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='prescribed_at',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='prescribed_by',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='customized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ajustada em'),
        ),
    ]
