# Generated by Django 5.2.17 on 2026-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_remove_trainingplan_prescribed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('barbell', 'barra'), ('dumbbell', 'halteres'), ('machine', 'máquina'), ('cable', 'polia'), ('bodyweight', 'peso do corpo')], default='machine', max_length=12, verbose_name='equipamento'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='joints',
            field=models.JSONField(blank=True, default=list, verbose_name='articulações exigidas'),
        ),
    ]
