# Generated by Django 5.2.17 on 2026-08-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_exercise_equipment_exercise_joints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='animation_url',
            field=models.URLField(blank=True, verbose_name='animação anatômica'),
        ),
    ]
