# Generated by Django 5.2.17 on 2026-09-02 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_alter_exercise_animation_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.CharField(max_length=64, verbose_name='identificador da operação')),
                ('comecou_em', models.DateTimeField(verbose_name='começou em')),
                ('terminou_em', models.DateTimeField(verbose_name='terminou em')),
                ('distancia_m', models.PositiveIntegerField(verbose_name='distância (m)')),
                ('duracao_s', models.PositiveIntegerField(verbose_name='duração (s)')),
                ('teve_lacuna', models.BooleanField(default=False, verbose_name='teve trecho não registrado')),
                ('parciais', models.JSONField(blank=True, default=list, verbose_name='parciais')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'corrida',
                'verbose_name_plural': 'corridas',
                'ordering': ['-comecou_em'],
                'indexes': [models.Index(fields=['user', '-comecou_em'], name='workouts_co_user_id_54bc43_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'op_id'), name='uma_corrida_por_operacao')],
            },
        ),
    ]
