# Generated by Django 5.2.17 on 2026-09-04 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_corrida'),
    ]

    operations = [
        migrations.CreateModel(
            name='TracoDaCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.JSONField(default=list, verbose_name='pontos')),
                ('descartadas', models.PositiveIntegerField(default=0, verbose_name='leituras descartadas')),
                ('corrida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traco', to='workouts.corrida', verbose_name='corrida')),
            ],
            options={
                'verbose_name': 'traçado da corrida',
                'verbose_name_plural': 'traçados das corridas',
            },
        ),
    ]
