# Generated by Django 5.2.17 on 2026-09-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    """TREINO V4, fase A: os três campos que faltavam. Só acrescenta.

    Nenhum `RunPython`, nenhum `RunSQL`, nenhum `AlterField`. Os 36 exercícios
    já cadastrados ganham `secondary_muscles = []` e os dois segundos em
    `NULL`, e `NULL` é o estado de verdade: significa "ninguém conferiu este
    vídeo ainda", e o player continua começando do zero — exatamente o
    comportamento de antes.

    `muscle_group` NÃO foi tocado. Ele continua sendo o grupo principal, e
    continua sendo de onde `muscle_volume` tira a conta. Renomeá-lo por
    simetria com o campo novo custaria uma migração de dados em cima do
    histórico inteiro para não melhorar nada.

    A reversão devolve as três colunas ao que eram: como nada foi escrito por
    esta migration, desfazê-la não deixa dado incoerente — só apaga o que for
    cadastrado depois dela, que é o que qualquer `RemoveField` faz.
    """

    dependencies = [
        ('workouts', '0015_tracodacorrida'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.JSONField(blank=True, default=list, help_text='Lista de grupos musculares auxiliares, da mesma taxonomia.', verbose_name='músculos secundários'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_end_seconds',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Opcional. Precisa ser maior que o início.', null=True, verbose_name='fim da execução (s)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_start_seconds',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Segundo em que a demonstração do movimento começa de verdade. Deixe vazio se você não assistiu ao vídeo para conferir.', null=True, verbose_name='início da execução (s)'),
        ),
    ]
