# Generated by Django 5.2.17 on 2026-09-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0018_aposenta_remada_curvada_com_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='main_groups',
            field=models.JSONField(blank=True, default=list, verbose_name='grupos anunciados'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='main_groups',
            field=models.JSONField(blank=True, default=list, verbose_name='grupos anunciados'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='split',
            field=models.CharField(choices=[('full', 'Corpo inteiro'), ('ab', 'AB — superior e inferior'), ('abc', 'ABC — empurrar, puxar e pernas'), ('abc2', 'ABC de dois grupos — peito/tríceps, costas/bíceps e pernas/ombros'), ('abcd', 'ABCD — peito/tríceps, costas/bíceps, ombro/perna e complementares'), ('abcde', 'ABCDE — o ciclo de quatro mais um dia de pontos fracos')], max_length=6, verbose_name='divisão'),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='split',
            field=models.CharField(choices=[('full', 'Corpo inteiro'), ('ab', 'AB — superior e inferior'), ('abc', 'ABC — empurrar, puxar e pernas'), ('abc2', 'ABC de dois grupos — peito/tríceps, costas/bíceps e pernas/ombros'), ('abcd', 'ABCD — peito/tríceps, costas/bíceps, ombro/perna e complementares'), ('abcde', 'ABCDE — o ciclo de quatro mais um dia de pontos fracos')], max_length=6, verbose_name='divisão'),
        ),
    ]
