# Generated by Django 5.2.17 on 2026-09-13 15:44

"""O rótulo do `Split.ABCDE` deixa de chamar o quinto dia de "pontos fracos".

Só o TEXTO das `choices` muda — o modelo ABCDE de hoje é um grupo por dia
(peito, costas, pernas, ombros, braços), não "o ciclo de quatro mais um dia".
`choices` faz parte do estado das migrations, então o Django exige esta
migration; no PostgreSQL ela é no-op (`sqlmigrate` imprime só BEGIN/COMMIT):
nenhuma coluna, nenhuma linha, nenhum valor muda.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0019_trainingsession_main_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='split',
            field=models.CharField(choices=[('full', 'Corpo inteiro'), ('ab', 'AB — superior e inferior'), ('abc', 'ABC — empurrar, puxar e pernas'), ('abc2', 'ABC de dois grupos — peito/tríceps, costas/bíceps e pernas/ombros'), ('abcd', 'ABCD — peito/tríceps, costas/bíceps, ombro/perna e complementares'), ('abcde', 'ABCDE — peito, costas, pernas, ombros e braços, um por dia')], max_length=6, verbose_name='divisão'),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='split',
            field=models.CharField(choices=[('full', 'Corpo inteiro'), ('ab', 'AB — superior e inferior'), ('abc', 'ABC — empurrar, puxar e pernas'), ('abc2', 'ABC de dois grupos — peito/tríceps, costas/bíceps e pernas/ombros'), ('abcd', 'ABCD — peito/tríceps, costas/bíceps, ombro/perna e complementares'), ('abcde', 'ABCDE — peito, costas, pernas, ombros e braços, um por dia')], max_length=6, verbose_name='divisão'),
        ),
    ]
