# Generated by Django 5.2.17 on 2026-09-15 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0020_rotulo_do_abcde'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionexercise',
            options={'ordering': ['opcao', 'order', 'id'], 'verbose_name': 'exercício da ficha', 'verbose_name_plural': 'exercícios da ficha'},
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='opcao',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='opção'),
        ),
        migrations.CreateModel(
            name='EscolhaDeTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('opcao', models.PositiveSmallIntegerField(default=1, verbose_name='opção')),
                ('versao', models.CharField(choices=[('completo', 'Treino completo'), ('rapido', 'Versão rápida')], default='completo', max_length=8, verbose_name='versão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolhas', to='workouts.trainingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolhas_de_treino', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'escolha de treino',
                'verbose_name_plural': 'escolhas de treino',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uma_escolha_de_treino_por_dia')],
            },
        ),
    ]
