# Generated by Django 5.2.17 on 2026-09-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0024_rotacao_continua_do_ciclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='origem',
            field=models.CharField(choices=[('gps', 'GPS'), ('manual', 'à mão')], default='gps', max_length=8),
        ),
        migrations.AddField(
            model_name='corrida',
            name='sensacao',
            field=models.CharField(blank=True, choices=[('leve', 'leve'), ('normal', 'normal'), ('pesada', 'pesada')], default='', max_length=8),
        ),
    ]
