# -*- coding: utf-8 -*-
"""`EventoDeProduto` (17/09/2026): um uso por pessoa, nome e dia de uma feature
em avaliacao - hoje so `versao_rapida`. Tabela nova, sem RunPython, sem tocar
em linha existente."""
# Generated by Django 5.2.17 on 2026-09-17 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0024_rotacao_continua_do_ciclo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDeProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='evento')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='dia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_de_produto', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'evento de produto',
                'verbose_name_plural': 'eventos de produto',
                'constraints': [models.UniqueConstraint(fields=('user', 'nome', 'date'), name='um_evento_por_pessoa_e_dia')],
            },
        ),
    ]
