# Generated by Django 5.2.17 on 2026-09-17 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0025_corrida_origem_sensacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoDeCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('5k', '5K'), ('10k', '10K')], max_length=3, verbose_name='plano')),
                ('nivel', models.CharField(choices=[('iniciante', 'iniciante'), ('intermediario', 'intermediário')], max_length=14, verbose_name='nível')),
                ('comecou_em', models.DateField(verbose_name='começou em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_de_corrida', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'plano de corrida',
                'verbose_name_plural': 'planos de corrida',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('user',), name='um_plano_de_corrida_ativo')],
            },
        ),
    ]
