# Generated by Django 5.2.17 on 2026-09-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0029_troca_de_exercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='progressao',
            field=models.JSONField(blank=True, default=dict, verbose_name='progressão do movimento'),
        ),
    ]
