# Generated by Django 5.2.17 on 2026-09-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0029_troca_de_exercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrida',
            name='origem',
            field=models.CharField(choices=[('gps', 'GPS'), ('manual', 'à mão'), ('arquivo', 'de arquivo')], default='gps', max_length=8),
        ),
    ]
