# Generated by Django 5.2.17 on 2026-09-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0030_alter_corrida_origem'),
        ('workouts', '0030_progressao_do_movimento'),
    ]

    operations = [
    ]
