# Generated by Django 5.2.17 on 2026-09-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0032_grupo_gluteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrida',
            name='origem',
            field=models.CharField(choices=[('gps', 'GPS'), ('manual', 'à mão'), ('arquivo', 'de arquivo'), ('aparelho', 'do aparelho')], default='gps', max_length=8),
        ),
    ]
