# Generated by Django 5.2.17 on 2026-09-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0033_corrida_origem_aparelho'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='regenerar_pedido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='remontagem pedida em'),
        ),
    ]
