# Generated by Django 5.2.17 on 2026-09-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0034_regenerar_pedido_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolhadetreino',
            name='encerrado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='encerrado em'),
        ),
    ]
