# Generated by Django 5.2.17 on 2026-09-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0035_treino_encerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='falhou',
            field=models.BooleanField(default=False, verbose_name='falhou'),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='observação'),
        ),
    ]
