# Generated by Django 5.2.17 on 2026-09-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0036_nota_e_falha_da_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='assistido',
            field=models.BooleanField(default=False, verbose_name='carga é assistência'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='measure',
            field=models.CharField(choices=[('reps', 'Repetições'), ('seconds', 'Segundos')], default='reps', max_length=8),
        ),
    ]
