# Generated by Django 5.2.17 on 2026-08-23 20:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='identificador')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('kind', models.CharField(choices=[('restriction', 'Restrição (filtra o que pode aparecer)'), ('preference', 'Preferência (só ordena as sugestões)')], default='restriction', max_length=12, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'restrição / preferência',
                'verbose_name_plural': 'restrições e preferências',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('brand', models.CharField(blank=True, max_length=80, verbose_name='marca')),
                ('base_unit', models.CharField(choices=[('g', 'Gramas'), ('ml', 'Mililitros')], default='g', max_length=2, verbose_name='unidade base')),
                ('kcal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='calorias (por 100)')),
                ('protein_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='proteína g (por 100)')),
                ('carb_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='carboidrato g (por 100)')),
                ('fat_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='gordura g (por 100)')),
                ('fiber_g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='fibra g (por 100)')),
                ('source', models.CharField(choices=[('manual', 'Cadastro manual'), ('taco', 'Tabela TACO'), ('off', 'Open Food Facts')], default='manual', max_length=10, verbose_name='fonte')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'alimento',
                'verbose_name_plural': 'alimentos',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'brand'), name='unique_food_name_brand')],
            },
        ),
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('category', models.CharField(choices=[('breakfast', 'Café da manhã'), ('main', 'Refeição principal (almoço/jantar)'), ('snack', 'Lanche'), ('supper', 'Ceia')], max_length=12, verbose_name='categoria')),
                ('prep_minutes', models.PositiveSmallIntegerField(default=10, verbose_name='tempo de preparo (min)')),
                ('instructions', models.TextField(blank=True, verbose_name='modo de preparo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('kcal_cache', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='calorias')),
                ('protein_g_cache', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='proteína (g)')),
                ('carb_g_cache', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='carboidrato (g)')),
                ('fat_g_cache', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='gordura (g)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='meal_templates', to='catalog.dietarytag', verbose_name='atende a')),
            ],
            options={
                'verbose_name': 'refeição (modelo)',
                'verbose_name_plural': 'refeições (modelos)',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='medida')),
                ('grams', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='equivale a (g/ml)')),
                ('is_default', models.BooleanField(default=False, verbose_name='medida padrão')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='catalog.food')),
            ],
            options={
                'verbose_name': 'medida caseira',
                'verbose_name_plural': 'medidas caseiras',
                'ordering': ['-is_default', 'grams'],
                'constraints': [models.UniqueConstraint(fields=('food', 'label'), name='unique_portion_per_food')],
            },
        ),
        migrations.CreateModel(
            name='MealTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantidade (g/ml)')),
                ('scalable', models.BooleanField(default=True, help_text='Marque para itens que podem crescer/diminuir junto com a meta calórica (arroz, frango). Desmarque para itens fixos (1 ovo, 1 fatia, tempero).', verbose_name='escalável')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_items', to='catalog.food')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.mealtemplate')),
            ],
            options={
                'verbose_name': 'ingrediente',
                'verbose_name_plural': 'ingredientes',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('template', 'food'), name='unique_food_per_template')],
            },
        ),
    ]
