# Generated by Django 5.2.17 on 2026-08-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtemplate',
            name='everyday',
            field=models.BooleanField(default=True, help_text='Marque para receitas de ingrediente barato e preparo direto (arroz com feijão e ovo, sanduíche de frango). Desmarque para as mais elaboradas ou caras — elas só entram no cardápio quando nenhuma simples serve.', verbose_name='comida do dia a dia'),
        ),
    ]
