# Generated by Django 5.2.17 on 2026-08-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_mealtemplate_everyday'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='aisle',
            field=models.CharField(choices=[('produce', 'Hortifrúti'), ('butcher', 'Açougue e ovos'), ('dairy', 'Laticínios e frios'), ('bakery', 'Padaria'), ('grocery', 'Mercearia')], default='grocery', help_text='Usado para agrupar a lista de compras na ordem em que se anda no mercado.', max_length=10, verbose_name='corredor do mercado'),
        ),
    ]
