# Generated by Django 5.2.17 on 2026-08-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_food_aisle'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='role',
            field=models.CharField(choices=[('protein', 'Fonte de proteína'), ('starch', 'Carboidrato do prato'), ('legume', 'Leguminosa'), ('fruit', 'Fruta'), ('vegetable', 'Legume ou verdura'), ('fat', 'Fonte de gordura'), ('dairy', 'Laticínio'), ('drink', 'Bebida'), ('other', 'Outro')], default='other', help_text='O que este alimento faz na refeição. É o que limita a substituição: só entra troca do mesmo papel.', max_length=10, verbose_name='papel no prato'),
        ),
    ]
