# Generated by Django 5.2.17 on 2026-08-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_papel_no_prato'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Marca peixe, atum, carne nobre, proteína de soja e derivados especiais. Quem escolhe o cardápio econômico recebe estes por último — não é restrição, é preço.', verbose_name='ingrediente caro ou difícil de achar'),
        ),
    ]
