# Generated by Django 5.2.17 on 2026-09-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_food_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodportion',
            name='plural',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='medida (plural)'),
        ),
        migrations.AddField(
            model_name='foodportion',
            name='singular',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='medida (singular)'),
        ),
    ]
