# Generated by Django 5.2.17 on 2026-09-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_porcao_singular_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtemplate',
            name='items_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ingredientes alterados em'),
        ),
    ]
