# Generated by Django 5.2.17 on 2026-09-23 12:54

from django.db import migrations, models


def preencher_pelo_nome(apps, schema_editor):
    """Toda receita que já existe ganha a família do nome dela.

    `default="prato"` deixaria as 38 receitas que NÃO são prato feito com o
    desenho errado até alguém rodar o seed — e o seed roda no build, mas a
    migration roda ANTES dele. Um deploy com o desenho errado em 38 cards é
    pior que um deploy a mais de trabalho aqui.

    A função é a mesma que o seed usa (`catalog.ilustracoes.familia_de`), e
    não uma cópia: duas respostas para "de que família é esta receita"
    divergiriam na primeira receita nova.
    """
    from catalog.ilustracoes import familia_de

    MealTemplate = apps.get_model("catalog", "MealTemplate")
    for receita in MealTemplate.objects.all().only("id", "name"):
        MealTemplate.objects.filter(pk=receita.pk).update(
            ilustracao=familia_de(receita.name)
        )


def voltar(apps, schema_editor):
    """Nada a desfazer: a coluna inteira some na reversa do AddField."""


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_mealtemplate_items_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtemplate',
            name='ilustracao',
            field=models.CharField(choices=[('cuscuz', 'Cuscuz'), ('mingau', 'Mingau'), ('ovos', 'Ovos'), ('pao', 'Pão e sanduíche'), ('tapioca', 'Tapioca'), ('vitamina', 'Vitamina'), ('prato', 'Prato feito'), ('macarrao', 'Macarrão'), ('iogurte', 'Iogurte'), ('fruta', 'Fruta'), ('salada', 'Salada')], default='prato', max_length=12, verbose_name='ilustração'),
        ),
        migrations.RunPython(preencher_pelo_nome, voltar),
    ]
