# Generated by Django 5.2.17 on 2026-09-22 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoNativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True, verbose_name='token do FCM')),
                ('plataforma', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=8)),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('visto_em', models.DateTimeField(blank=True, null=True, verbose_name='último envio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_nativos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dispositivo nativo',
                'verbose_name_plural': 'dispositivos nativos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
